### ISSUE TITLE
Build a single page app calling the Zeno API

### ISSUE THREAD

**Issue by yellowcap** [wri/project-zeno#11]
Build a single page app that can show data returned by one of the agents. A few ideas:

- Accepts text prompts for searching areas
- Pulls in and renders statistics from Zeno in a graph
- Shows DIST alerts
- Displays textual summary of data as returned by LLM

**Comment by geohacker** [comment]
@yellowcap @srmsoumya and I talked through this a bit in Lisbon. Here's one proposal that we can start working on to get the frontend work going:

* User Inputs to the API — text, map bounds, bounding box or a point 
* Content Types — the backend will return content type without making any assumptions about the way it should be rendered. The frontend will decide how to render what content and also provide additional options if needed, for example a CSV could be rendered as a table, line chart, bar chart, or even as a choropleth on the map.
* Renderers — the frontend starts with a basic set of renderers. Maps and charts.

@yellowcap shared this in slack already but I'll post here:

```
[
    {
        "type": "csv",
        "data": [....]
    },
    {
        "type": "geojson",
        "data": [....]
    },
    {
        "type": "layers",
        "data": [{"name": "layer1", "url": "abc.com/z/x/y"}, ]
    },
    {
        "type": "text",
        "data": "This is trending upwards",
        "style": {...}
    }
]
```

In the future, this structure would allow us to define:
* More content types
* Specific style specifications for layers (we'll likely stick to a schema like MapLibre)
* Full rendering control and actions on the frontend

**Comment by yellowcap** [comment]
I updated the descption in light of the 🎄 milestone. We can ticket this out in more detail as we move forward @kamicut

**Comment by yellowcap** [comment]
Frontend repo was created https://github.com/wri/project-zeno-frontend
