### ISSUE TITLE
Working with the GFW APIs

### ISSUE THREAD

**Issue by geohacker** [wri/project-zeno#13]
Just documenting things as I get upto speed with the GFW APIs. There are two API (as I just discovered on the call with @01painadam):

## Data API (data-api.globalforestwatch.org)
I created a bot account with `sajjad+bot@developmentseed.org` to generate access token and api key. All are stored in the DevSeed DevOps 1password vault.

* API docs https://data-api.globalforestwatch.org/
* openAPI schema to feed into the agent https://data-api.globalforestwatch.org/openapi.json
* Looks like a FastAPI backend
* API key / access token seem interchangeable. Use them as `--header 'Authorization: Bearer <token>'`

## GFW Application API (globalforestwatch.org/api/gfw/v1)
@01painadam  could we get access to the API docs for this? Also perhaps it's good to give the team a heads up that we intend to use this API programmatically, outside of the GFW frontend, we could potentially use a `application=project-zeno` if that's helpful!

cc @yellowcap @srmsoumya @leothomas @LanesGood @sunu

**Comment by 01painadam** [comment]
Thanks @geohacker:

The Application API is aliasing resourcewatch api and drives the front-end map layers. Docs here https://resource-watch.github.io/doc-api/reference.html#resource-watch-api-reference

**Comment by yellowcap** [comment]
Tabeling this in favor of GEE driven agents for now, lets reopen when going back to GFW.
