### ISSUE TITLE
Langchain Agent: Search and return GFW data via Data API

### ISSUE THREAD

**Issue by LanesGood** [wri/project-zeno#2]
Baseline Langchain Agent: search and return GFW data via Data API (base implementation)

This agent gets the actual data (statistics) from specific layers over specific date ranges and locations.

**Comment by LanesGood** [comment]
This is likely too broad: refinement below.

Most important function tool = given user placename query, (country/region/subregion), provide stats on datasets, filters for place & year

4 main tools:
- Location - given any place, query data API for polygon (built)
- Query DataAPI for GADM GLAD Admin2 Weekly Alerts tool

**Comment by yellowcap** [comment]
Partially implemented, and tabled in favor of GEE driven agents.
