### ISSUE TITLE
Wireframes for the first alerting workflow

### ISSUE THREAD

**Issue by yellowcap** [wri/project-zeno#25]
Develop the UX perspective on how a user can find an area and obtain statistics on DIST alerts for that area.

**Comment by jjyutm4532** [comment]
Hello, I tried to solve the issue.

This is what I did:

Implement location search functionality and display GLAD alerts statistics for the selected area in the frontend.

You can review changes in this commit: https://github.com/jjyutm4532/wri-project-zeno-25/commit/5599ae66c9a85f79d15650d13c561ae633deb705.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by LanesGood** [comment]
The wireframes are available as a clickable prototype here: https://www.figma.com/proto/N20cpSWt9kWZWILQOcsdIT/WRI_LCL_ProjectZeno?page-id=8%3A3&node-id=53-385&node-type=frame&viewport=-2225%2C-2828%2C0.46&t=xzUHx92Qk2Zx6Gu4-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=53%3A385&show-proto-sidebar=1

@yellowcap @01painadam I'll share these in our session tomorrow, and welcome any comments or feedback directly in the figma prior to our discussion or after.
