### ISSUE TITLE
Graphical designs for first alert workflow

### ISSUE THREAD

**Issue by yellowcap** [wri/project-zeno#26]
Develop a graphical design layer on top of the wireframes developed in #25

**Comment by LanesGood** [comment]
High-fidelity explorations of the main interface:
- Map as full-screen background with floating chat panel
![image](https://github.com/user-attachments/assets/a41b83d6-0dc6-458b-afc7-0e7941016d1a)

- Map as panel with floating chat panel
![image](https://github.com/user-attachments/assets/4614e781-e3f6-4999-a2d6-74a954478f18)

Pattern sheet (in progress)
![image](https://github.com/user-attachments/assets/ce2d5555-b463-46bf-a2e0-712259b93860)

cc @yellowcap @01painadam

**Comment by 01painadam** [comment]
nice, thanks @LanesGood! Is there a figma file you could share?

I'm conflicted on the full screen vs. panel map. On the one hand having a full screen map make it feel like the map is important, font-and center. Plus (I know it's rough right now) but I actually like the translucent chat panel used in the FE
 
 ![Screenshot 2024-12-13 at 11 27 43](https://github.com/user-attachments/assets/3bcb5f73-5a0b-4d43-a15b-708256cc012a)
 Again, it makes the map feel central.
 
The problem I have with it is, how do we transition from this view when the map _isn't_ the centrepiece (e.g. when we are more interested in say a dahsboard-view). I feel that the second option makes more sense as we can bring in and resize panels based on whats coming back from the LLM. Might be interesting to explore some of these transitioning in the next wireframes. e.g.

- Given that the user has prompted for an analysis, when the data resolves, the map panel minimises and a dashboard (charts) panel appears and expands
- Given that the user has asked for relevant datasets, when the LLM returns the response, the map panel closes and the bat panel fills the screen to show detailed text descriptions of suggested datasets

Thoughts?

**Comment by LanesGood** [comment]
I do feel that we should allow for the expansion/addition of charts, dashboard widgets, tables, etc. For this reason, I think containing the map is the right choice. It also helps make the application (the prototype at least) feel more distinct from GFW. Further exploration of expansion/contraction of these components could also be interesting, and continues in the [figma file](https://www.figma.com/design/N20cpSWt9kWZWILQOcsdIT/WRI_LCL_ProjectZeno?node-id=217-1216&t=49S0jPbN2avd7tsL-1).
