### ISSUE TITLE
Langchain Agent: Knowledge base

### ISSUE THREAD

**Issue by LanesGood** [wri/project-zeno#5]
Langchain agent: Guide user understanding of the GFW data API docs. LLM can understand and guide users through docs about:
- GFW API
- GFW Terms
- User guide for frontend application (test scenario)

Here are sub-tasks

- [ ] https://github.com/wri/project-zeno/issues/8
- [x] https://github.com/wri/project-zeno/issues/7

**Comment by yellowcap** [comment]
The layerfinder agent does this, and we can focus on adding more docs to the docfinder in #8
