### ISSUE TITLE
Identify and collect documents to be included in RAG pipeline

### ISSUE THREAD

**Issue by yellowcap** [wri/project-zeno#8]
We need to identify what documents we want to initially include in the RAG Pipeline component https://github.com/wri/project-zeno/issues/7

Ideally for a first iteration we would put these as static files in a shared folder. Examples are

- Blog posts as markdown
- PDF documents such as research papers etc
- Documentation about GFW also in markdown or equivalent

@01painadam assigining you for now to identify what we should include initially.

**Comment by 01painadam** [comment]
Collecting data here https://gfw.atlassian.net/wiki/external/MjAzYzcyNzZhZWEwNDRkOGI5MWZlODAwMGY1NzZhNTk

I'll open a folder in the shared drive
