### ISSUE TITLE
Build baseline Zeno API

### ISSUE THREAD

**Issue by yellowcap** [wri/project-zeno#9]
This api will be the interface people use to interact with the agents built in #1 .

Initially this could be a single API endpoint, delegating "routing" to different agents to the LLM as well. We can split this up into more fine grained API endpoints if needed, but initially we should try and rely on the LLM to select the agent workflow that makes most sense based on the user prompt.

**Comment by geohacker** [comment]
I suggest that use FastAPI here for the framework. With a PostgreSQL database.

**Comment by yellowcap** [comment]
We have a first version online. Now its getting the *right* api online :-)
